import type { Provider } from "../config.ts";
import type { CredentialManager } from "../auth/credential-manager.ts";
import type { AuthStore } from "../auth/store.ts";
import { CODEX_MODELS_URL, codexHeaders } from "./constants.ts";
import { asRecord } from "./wire.ts";
export interface ModelDescriptor {provider:Provider;id:string;displayName:string;contextWindow?:number;maxOutputTokens?:number;reasoning?:readonly string[];priority?:number;eligibleAccounts?:readonly string[];}
export class ModelCatalog {
 constructor(private readonly credentials:CredentialManager,private readonly store:AuthStore,private readonly fetcher:typeof fetch=fetch,private readonly now=Date.now){}
 async discover(force=false):Promise<ModelDescriptor[]>{const lease=await this.credentials.lease();const cached=this.store.getModelCache(lease.accountId);if(!force&&cached&&this.now()-cached.fetchedAt<300_000)return normalizeModels(cached.payload,lease.accountId);try{const response=await this.fetcher(CODEX_MODELS_URL,{headers:{...codexHeaders(lease.accessToken,lease.accountId,lease.residency),...(cached?.etag?{"if-none-match":cached.etag}:{})}});if(response.status===304&&cached)return normalizeModels(cached.payload,lease.accountId);if(!response.ok)throw new Error(`Model discovery failed (${response.status})`);const payload:unknown=await response.json();const models=normalizeModels(payload,lease.accountId);if(this.store.getCredential(lease.accountId))this.store.putModelCache(lease.accountId,payload,this.now(),response.headers.get("etag")??undefined);return models;}catch(error){if(cached&&this.now()-cached.fetchedAt<86_400_000)return normalizeModels(cached.payload,lease.accountId);throw error;}}
}
export function normalizeModels(payload:unknown,accountId?:string):ModelDescriptor[]{const root=asRecord(payload,"Malformed model catalog");const entries=Array.isArray(root.models)?root.models:Array.isArray(root.data)?root.data:[];const result:ModelDescriptor[]=[];for(const raw of entries){if(!raw||typeof raw!=="object")continue;const r=raw as Record<string,unknown>;const id=typeof r.slug==="string"?r.slug:typeof r.id==="string"?r.id:"";if(!id||r.hidden===true||r.visible===false)continue;const descriptor:ModelDescriptor={provider:"openai-codex",id,displayName:typeof r.display_name==="string"?r.display_name:id};if(Number.isFinite(r.context_window))descriptor.contextWindow=Number(r.context_window);if(Number.isFinite(r.max_output_tokens))descriptor.maxOutputTokens=Number(r.max_output_tokens);if(Number.isFinite(r.priority))descriptor.priority=Number(r.priority);if(accountId)descriptor.eligibleAccounts=[accountId];const levels=r.reasoning_levels;if(Array.isArray(levels))descriptor.reasoning=levels.filter((x):x is string=>typeof x==="string");result.push(descriptor);}return result.sort((a,b)=>(b.priority??0)-(a.priority??0)||a.id.localeCompare(b.id));}
