import type { CredentialLease } from "../auth/types.ts";
import { CredentialManager } from "../auth/credential-manager.ts";
import { CODEX_RESPONSES_URL, codexHeaders } from "./constants.ts";
import { decodeSSE } from "./sse.ts";
import { installationId } from "./installation.ts";
import { asRecord, stringField, type CodexFunctionCall, type CodexOutputItem, type CodexRequest, type CodexTurnResponse } from "./wire.ts";

export interface CodexTransportOptions { credentials:CredentialManager; fetch?:typeof fetch; endpoint?:string; installationId?:string; sessionId?:string; }
export class CodexHttpError extends Error { constructor(readonly status:number,message:string,readonly retryAfter?:number){super(message);} }

export class CodexTransport {
 private readonly fetcher:typeof fetch;private readonly endpoint:string;readonly installationId:string;readonly sessionId:string;
 constructor(private readonly options:CodexTransportOptions){this.fetcher=options.fetch??fetch;this.endpoint=options.endpoint??CODEX_RESPONSES_URL;this.installationId=options.installationId??installationId();this.sessionId=options.sessionId??crypto.randomUUID();}
 async createResponse(request:CodexRequest,signal?:AbortSignal):Promise<CodexTurnResponse>{let auth=await this.options.credentials.lease(request.model);let refreshed=false,rotated=false,transientAttempts=0;for(;;){let response:Response;try{response=await this.post(request,auth,signal);}catch(error){if(signal?.aborted||transientAttempts++>=2)throw error;await this.delay(200*2**transientAttempts,signal);continue;}if(response.status===401&&!refreshed){refreshed=true;await this.options.credentials.refresh(auth.accountId,true);auth=await this.options.credentials.lease(request.model);continue;}if(response.status===429){const retry=this.retryAfter(response);this.options.credentials.recordBlocked(auth.accountId,429,Date.now()+(retry??60_000));if(!rotated){rotated=true;this.options.credentials.invalidateAffinity();auth=await this.options.credentials.lease(request.model);continue;}}if(response.status>=500&&transientAttempts++<2){await this.delay(this.retryAfter(response)??200*2**transientAttempts,signal);continue;}if(!response.ok)throw await this.httpError(response);if(!response.body)throw new Error("Codex response had no event stream");return this.accumulate(response.body);}}
 private delay(ms:number,signal?:AbortSignal):Promise<void>{return new Promise((resolve,reject)=>{if(signal?.aborted){reject(signal.reason);return;}const timer=setTimeout(resolve,ms);signal?.addEventListener("abort",()=>{clearTimeout(timer);reject(signal.reason);},{once:true});});}
 private post(body:CodexRequest,auth:CredentialLease,signal?:AbortSignal):Promise<Response>{return this.fetcher(this.endpoint,{method:"POST",headers:{...codexHeaders(auth.accessToken,auth.accountId,auth.residency),"content-type":"application/json",accept:"text/event-stream","x-codex-installation-id":this.installationId,"x-codex-routing-hint":`model=${body.model}`,"session-id":this.sessionId,"thread-id":this.sessionId},body:JSON.stringify(body),signal});}
 private async httpError(response:Response):Promise<CodexHttpError>{let detail="";try{const text=await response.text();if(text){try{const payload=JSON.parse(text) as Record<string,unknown>;const nested=payload.error&&typeof payload.error==="object"?payload.error as Record<string,unknown>:undefined;const value=nested?.message??payload.detail??payload.message??payload.error;detail=typeof value==="string"?value:text;}catch{detail=text;}}}catch{}detail=detail.replace(/\s+/g," ").trim().slice(0,1000);const requestId=response.headers.get("x-request-id");const suffix=[detail,requestId?`request ID: ${requestId}`:""] .filter(Boolean).join("; ");return new CodexHttpError(response.status,`Codex request failed (${response.status})${suffix?`: ${suffix}`:""}`,this.retryAfter(response));}
 private retryAfter(response:Response):number|undefined{const raw=response.headers.get("retry-after");if(!raw)return;const seconds=Number(raw);if(Number.isFinite(seconds))return seconds*1000;const date=Date.parse(raw);return Number.isFinite(date)?Math.max(0,date-Date.now()):undefined;}
 private async accumulate(stream:ReadableStream<Uint8Array>):Promise<CodexTurnResponse>{let id="",status="incomplete",text="";const output:CodexOutputItem[]=[];const calls=new Map<string,CodexFunctionCall>();const summaries:string[]=[];let usage:CodexTurnResponse["usage"];
  for await(const event of decodeSSE(stream)){if(event.data==="[DONE]")continue;let value:Record<string,unknown>;try{value=asRecord(JSON.parse(event.data));}catch{throw new Error("Malformed JSON in Codex event stream");}const type=stringField(value,"type")??event.event??"";if(type==="error"||type==="response.failed"){const error=value.error&&typeof value.error==="object"?value.error as Record<string,unknown>:value;throw new Error(`Codex stream error: ${stringField(error,"message")??"unknown error"}`);}if(type.includes("output_text.delta")){text+=stringField(value,"delta")??"";}else if(type.includes("reasoning_summary_text.delta")||type.includes("reasoning_summary.delta")){const delta=stringField(value,"delta");if(delta)summaries.push(delta);}else if(type==="response.output_item.added"||type==="response.output_item.done"){const item=asRecord(value.item);if(item.type==="function_call"){const key=String(item.call_id??item.id??value.output_index);const call:{type:"function_call";id?:string;call_id:string;name:string;arguments:string}={type:"function_call",call_id:String(item.call_id??item.id??""),name:String(item.name??""),arguments:String(item.arguments??"")};if(typeof item.id==="string")call.id=item.id;calls.set(key,call);if(item.id!==undefined)calls.set(String(item.id),call);if(item.call_id!==undefined)calls.set(String(item.call_id),call);if(value.output_index!==undefined)calls.set(String(value.output_index),call);}else if(type.endsWith("done"))output.push(item);}else if(type.includes("function_call_arguments.delta")){const key=String(value.call_id??value.item_id??value.output_index);const found=calls.get(key)??{type:"function_call",call_id:String(value.call_id??value.item_id??""),name:String(value.name??""),arguments:""};found.arguments+=stringField(value,"delta")??"";calls.set(key,found);}else if(type==="response.completed"){const response=asRecord(value.response);id=stringField(response,"id")??id;status=String(response.status??"completed");if(!text&&typeof response.output_text==="string")text=response.output_text;const u=response.usage;if(u&&typeof u==="object"){const r=u as Record<string,unknown>;usage={inputTokens:Number(r.input_tokens??0),outputTokens:Number(r.output_tokens??0),totalTokens:Number(r.total_tokens??0)};}}}
  output.push(...new Set(calls.values()));if(status!=="completed")throw new Error("Codex event stream ended before a completed response");return{id,status:"completed",output,outputText:text,reasoningSummaries:summaries,usage}; }
}
